-- Auto-generated by hadalized v0.5.4
-- WARNING: Do not edit by hand.

-- By setting our module to nil, we clear lua's cache,
-- which means the require ahead will *always* occur.
--
-- This isn't strictly required but it can be a useful trick if you are
-- incrementally editing your config a lot and want to be sure your themes
-- changes are being picked up without restarting neovim.
--
-- Note if you're working in on your theme and have :Lushify'd the buffer,
-- your changes will be applied with or without the following line.
--
-- The performance impact of this call can be measured in the hundreds of
-- *nanoseconds* and such could be considered "production safe".
--

---@type Palette
local palette = {
  name = "hadalized-day",
  desc = "Light theme variant with sunny backgrounds.",
  version = "2.1",
  mode = "light",
  gamut = "srgb",
  aliases = {
    "day",
  },
  hue = {
    red = "#c73335",
    orange = "#d0750a",
    yellow = "#a0902a",
    lime = "#8d982b",
    green = "#598a00",
    mint = "#3fa66b",
    cyan = "#008474",
    azure = "#2d9dc1",
    blue = "#297cc7",
    violet = "#7456d4",
    magenta = "#aa3ea4",
    rose = "#b96d85",
  },
  base = {
    bg = "#fffef6",
    bg1 = "#fdfcf5",
    bg2 = "#f1efe0",
    bg3 = "#e9e7d8",
    bg4 = "#fdfcf5",
    bg5 = "#d0cec0",
    bg6 = "#c0beb0",
    hidden = "#a7b0b2",
    subfg = "#7a8284",
    fg = "#282f31",
    emph = "#111719",
    op2 = "#04191f",
    op1 = "#001117",
    op = "#00090e",
  },
  bright = {
    red = "#fa5654",
    orange = "#fc8e05",
    yellow = "#d7bf0a",
    lime = "#afce19",
    green = "#81d943",
    mint = "#14e184",
    cyan = "#02dbc1",
    azure = "#40cfff",
    blue = "#8cc3fc",
    violet = "#bcb3fa",
    magenta = "#fe8df6",
    rose = "#fd9cba",
  },
  hl = {
    red = "#f8a49d",
    orange = "#ffbe8a",
    yellow = "#fff19b",
    lime = "#cdd88b",
    green = "#b8db96",
    mint = "#a0eab9",
    cyan = "#8ff4e0",
    azure = "#99e2ff",
    blue = "#98cbff",
    violet = "#c4bcff",
    magenta = "#ff9df7",
    rose = "#ffa9c3",
  },
  gs = {
    black = "#010405",
    darkgray = "#282f31",
    neutralgray = "#5d6567",
    lightgray = "#98a0a3",
    white = "#fbfeff",
  },
}


package.loaded['hadalized'] = nil
require('hadalized').load({palette = palette})
