-- Auto-generated by hadalized v0.5.4
-- WARNING: Do not edit by hand.

-- By setting our module to nil, we clear lua's cache,
-- which means the require ahead will *always* occur.
--
-- This isn't strictly required but it can be a useful trick if you are
-- incrementally editing your config a lot and want to be sure your themes
-- changes are being picked up without restarting neovim.
--
-- Note if you're working in on your theme and have :Lushify'd the buffer,
-- your changes will be applied with or without the following line.
--
-- The performance impact of this call can be measured in the hundreds of
-- *nanoseconds* and such could be considered "production safe".
--

---@type Palette
local palette = {
  name = "hadalized-gray",
  desc = "Dark theme variant with more grayish backgrounds.",
  version = "2.1",
  mode = "dark",
  gamut = "srgb",
  aliases = {
    "gray",
  },
  hue = {
    red = "#d94543",
    orange = "#d0750a",
    yellow = "#b0a03c",
    lime = "#959f40",
    green = "#6da21c",
    mint = "#56bb7f",
    cyan = "#38a391",
    azure = "#4bb4da",
    blue = "#318bde",
    violet = "#896ded",
    magenta = "#c256bc",
    rose = "#d2849c",
  },
  base = {
    bg = "#060808",
    bg1 = "#070a0a",
    bg2 = "#0b0e0f",
    bg3 = "#141718",
    bg4 = "#1f2223",
    bg5 = "#2b2e30",
    bg6 = "#383b3c",
    hidden = "#4f5759",
    subfg = "#98a0a3",
    fg = "#bebeba",
    emph = "#cececa",
    op2 = "#c0beb0",
    op1 = "#d0cec0",
    op = "#e1dfd0",
  },
  bright = {
    red = "#fa5654",
    orange = "#fc8e05",
    yellow = "#d7bf0a",
    lime = "#afce19",
    green = "#81d943",
    mint = "#14e184",
    cyan = "#02dbc1",
    azure = "#40cfff",
    blue = "#8cc3fc",
    violet = "#bcb3fa",
    magenta = "#fe8df6",
    rose = "#fd9cba",
  },
  hl = {
    red = "#f8a49d",
    orange = "#ffbe8a",
    yellow = "#fff19b",
    lime = "#cdd88b",
    green = "#b8db96",
    mint = "#a0eab9",
    cyan = "#8ff4e0",
    azure = "#99e2ff",
    blue = "#98cbff",
    violet = "#c4bcff",
    magenta = "#ff9df7",
    rose = "#ffa9c3",
  },
  gs = {
    black = "#010405",
    darkgray = "#282f31",
    neutralgray = "#5d6567",
    lightgray = "#98a0a3",
    white = "#fbfeff",
  },
}


package.loaded['hadalized'] = nil
require('hadalized').load({palette = palette})
